### ISSUE TITLE
Frequency reordering

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/ringbuffer#11]
For a certain type of testing, we will have _wrong_ channel indices in the packet headers (this is the duplicate beamlet issue as mentioned in an email thread). It would be good to have an optional argument to fix the indices. It is possible to calculate the proper frequency channel from the value in the header, but maybe it is more useful to just have a list of nchan numbers that map the header channel index to the proper channel index? FYI this is the (repeating) pattern (where a beamlet = 4 channels for SC1 or 1 channel for SC1):

| beamlet in header | actual beamlet |
|-------------------|----------------|
| 0                 | 0              |
| 1                 | 1              |
| 2                | 2              |
| 3                 | 3              |
| 4                 | 3              |
| 5                 | 3              |

**Comment by jiskattema** [comment]
Judging from the table, the 'wrong' channel indices are a duplication of beamlet 3 into beamlets 4 and 5. Is it really worth it to complicate the code with an extra lookup table? Do you expect more 'wrong channel' situations, or would a simple switch that ignores beamlets 4 and 5 be enough?

Also, what should happen with the unwritten beamlets 4 and 5? Ringbuffer pages do not get cleared. So if beamlets 4 and 5 are not written you get data from the previous time the page was used; and if it is never written you get the initial values. Depending on the initialization of the ringbuffer, this can be zeros or noise. There is no missing value indicator, but possibly zeros are treated that way?

**Comment by loostrum** [comment]
The duplication of beamlet 3 into 4 and 5 is part of the issue, but I should have put the next set of 6 beamlets in the table as well to illustrate the second part of the issue:

| beamlet in header | actual beamlet |
|-------------------|----------------|
| 6                 | 4              |
| 7                | 5              |
| 8                | 6              |
| 9                 | 7              |
| 10                 | 7              |
| 11                 | 7              |

So beamlets 4 and 5 are not missing but shifted into the next set of 6 beamlets. This repeats as well so for every next set of 6 beamlets they are shifted more and more. Once we reach the last beamlet in the header, 383, the data is actually only at beamlet 255 (and all beamlets from 0 to 255 are present). The missing beamlets are 256-383. It would be best if these are zeroes, which is I think what I've seen so far if we're using e.g. not all uniboards which also causes part of the band to be missing. The offline data processing software picks that up correctly and masks it. For AMBER we could put those in the zapped_channels file to avoid it using them.

Here's a python snippet that calculates the data channel given the header channel (for SC4):
```beamlet_size = 4  # channels
header_beamlet = header_channel // beamlet_size
channel_in_beamlet = header_channel % beamlet_size
x = header_beamlet % 6  # location of beamlet in pattern of 6
y = header_beamlet // 6  # how many times the pattern was already repeated 
if x in (4, 5):
    # duplicate
    data_channel = -1
else:
    data_beamlet = 4 * y + x  # 4 good beamlets per pattern
    data_channel = data_beamlet * beamlet_size + channel_in_beamlet
```

**Comment by jiskattema** [comment]
ok, i start to understand the issue ;). So the information in the header is wrong, and the above code shows how to get to the correct freuquencies. 
Can you confirm the actual (real) frequencies changed do not change? ie. things like min_freq, max_freq, bandwidth etc? 

Easiest solution would be to have  a channel remapping file:
* we read the channel offset from the package header, and add the index in the package (ie. 0 to 5).
* we lookup the channel in the table, and replace it with the remapped value

**Comment by loostrum** [comment]
Yes, min_freq etc stay the same.
I could create a list of 1536 numbers that are the data channels for each header channel, or -1 for a duplicate. Then you can decide what the best way is to use this remapping table

**Comment by loostrum** [comment]
Here are the channel remappings for both SC1 and SC4:
[channel_remapping_sc1.txt](https://github.com/AA-ALERT/ringbuffer/files/2045109/channel_remapping_sc1.txt)
[channel_remapping_sc4.txt](https://github.com/AA-ALERT/ringbuffer/files/2045110/channel_remapping_sc4.txt)

**Comment by loostrum** [comment]
Taken care of offline in SC1. Already fixed in SC4 but that is a separate repository now.
