### ISSUE TITLE
SC4 timestamp should be in nr of packets

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/ringbuffer#2]
Currently, the timestamp used in SC3/4 is the unix timestamp but the packets contain the timestamp in units of (1.28 us) packets.

**Comment by jiskattema** [comment]
We also need to convert the start time from unix timestamp (given at the command line) into packets numbers, see the PDF:

> The Timestamp field is generated by the ARTS BF and contains an unsigned 64 bit integer number; this number represents the number of units of 1.28 μs that have elapsed since the midnight of the 1st of January 1970.

**Comment by loostrum** [comment]
Currently I'm giving the commandline start time already in number of
packets, but that could also be unix timestamp with conversion in the
fill_ringbuffer code of course -- up to you.

2017-06-20 10:42 GMT+02:00 Jisk Attema <notifications@github.com>:

**Comment by jiskattema** [comment]
Yes, you are right. Using the packet number is more precise than using timestamps, as the packet number is the thing that is actually used.
I'll update commandline arguments to make clear they are packet numbers, not times.

**Comment by loostrum** [comment]
Ok! Note that I already made a fix for the issues assigned to me in the
IAB_dev branch - you could merge those into sc4 (after checking I haven't
made any stupid mistakes ;) )

2017-06-20 10:58 GMT+02:00 Jisk Attema <notifications@github.com>:
